UPDATE restaurants SET comment = 'Ocakbaşı lezzeti çok iyiydi, kesinlikle tekrar giderim.' WHERE id = 'gm-01';
UPDATE restaurants SET comment = 'Şık bir mekan, yemekler de fena değildi.' WHERE id = 'gm-02';
UPDATE restaurants SET comment = 'Boyozu tam kıvamında, kahvaltı için harika bir durak.' WHERE id = 'gm-03';
UPDATE restaurants SET comment = 'Köfteleri gerçekten lezzetli, fiyatı da gayet uygun.' WHERE id = 'gm-04';
UPDATE restaurants SET comment = 'Sıcacık gevreği kaçırılmaz, İzmir''e gidince mutlaka uğrarım.' WHERE id = 'gm-05';
UPDATE restaurants SET comment = 'Balık taze ve pişirmesi ustaca, önerdiğim bir yer.' WHERE id = 'gm-06';
UPDATE restaurants SET comment = 'Atmosferi ve yemekleri çok başarılı, keyifli bir akşam yemeği.' WHERE id = 'gm-07';
UPDATE restaurants SET comment = 'Sakin bir mekan, yemekleri de gayet doyurucuydu.' WHERE id = 'gm-08';
UPDATE restaurants SET comment = 'Etleri gerçekten kaliteli, kasap-restoran kombinasyonu iyi çalışmış.' WHERE id = 'gm-09';
UPDATE restaurants SET comment = 'Uzun Çarşı''nın klasiklerinden, kebabı çok lezzetliydi.' WHERE id = 'gm-10';
UPDATE restaurants SET comment = 'Künefesi tam kıvamında, Antakya''da mutlaka denenmeli.' WHERE id = 'gm-11';
UPDATE restaurants SET comment = 'Lahmacunu ince ve lezzetli, hızlıca atıştırmak için ideal.' WHERE id = 'gm-12';
UPDATE restaurants SET comment = 'Ev yemekleri tadında, samimi bir lokanta.' WHERE id = 'gm-13';
UPDATE restaurants SET comment = 'Mangal ürünleri taze ve lezzetli, ailece gidilebilecek bir yer.' WHERE id = 'gm-14';
UPDATE restaurants SET comment = 'Deniz manzarası eşliğinde güzel bir yemek deneyimi.' WHERE id = 'gm-15';
UPDATE restaurants SET comment = 'Bozcaada''da denediğim en iyi balık yerlerinden biri.' WHERE id = 'gm-16';
UPDATE restaurants SET comment = 'Servisi ve yemekleri gayet tatmin ediciydi.' WHERE id = 'gm-17';
UPDATE restaurants SET comment = 'Şişleri nefis, porsiyonlar da doyurucu.' WHERE id = 'gm-18';
UPDATE restaurants SET comment = 'Kilis tavası burada gerçekten farklı, mutlaka denenmeli.' WHERE id = 'gm-19';
UPDATE restaurants SET comment = 'Ev yemeği tadında, sıcak bir ortamı var.' WHERE id = 'gm-20';
UPDATE restaurants SET comment = 'Uzun Çarşı''nın vazgeçilmezlerinden, eti çok lezzetli.' WHERE id = 'gm-21';
UPDATE restaurants SET comment = 'Manzarası ve ortamı çok keyifli, ailece gidilebilir.' WHERE id = 'gm-22';
UPDATE restaurants SET comment = 'Balık ekmek dendiğinde akla gelen ilk yerlerden, çok lezzetli.' WHERE id = 'gm-23';
UPDATE restaurants SET comment = 'Ocakbaşı ürünleri taze ve lezzetli, kasaptan direkt sofraya.' WHERE id = 'gm-24';
